package dev.lpa;

import java.util.HashSet;
import java.util.Set;

public class Contact {

    private String name;
    private Set<String> emails = new HashSet<>();
    private Set<String> phones = new HashSet<>();

    public Contact (String name){
        this (name, null);
    }

    public Contact (String name, String email){
        this(name, email, 0);

    }
    public Contact (String name, long phone){
        this(name, null,phone);
    }

    public Contact( String name, String email, long phone){

        this.name = name;
        if (email != null){
            emails.add(email);
        }

        if (phone > 0){
            String p = String.valueOf(phone);
            p = "(%s)%s-%s".formatted(p.substring(0,3), p.substring(3, 6), p.substring(6));
            phones.add(p);
        }
    }

    public String getName (){
        return this.name;
    }

    @Override
    public String toString(){
        return "%s: %s %s".formatted(name,emails,phones);
    }

    public Contact mergeContactData (Contact contact){

        Contact newContact = new Contact(name);
        newContact.emails = new HashSet<>(this.emails);
        newContact.phones = new HashSet<>(this.phones);
        newContact.emails.addAll(emails);
        newContact.phones.addAll(phones);
        return newContact;
    }

    //The equals and hashCode methods are used in Set collection to verify duplicates
    //Once a class has many fields and variables, you can choose what field will be checked for duplicates

    //Autogenerated by Intellij
    @Override
    public final boolean equals(Object object) {
        if (!(object instanceof Contact contact)) return false;

        return getName().equals(contact.getName());
    }
    //Autogenerated by Intellij
    @Override
    public int hashCode() {
        return 31 * getName().hashCode();
    }


    public void addEmail (String companyName){
        String[] names = name.split(" ");
        String email = "%c%s@%s.com".formatted(name.toLowerCase().charAt(0), names[names.length -1].toLowerCase(),
                companyName.replaceAll(" ", "").toLowerCase());
        if (!emails.add(email)) {
            System.out.println("Email was already added before! " + email);
            emails.add(email);
        } else {
            System.out.println("Email added! " + email);
        }
    }
}
